jpackage `
  --name desktopLogin `
  --app-version 2.0 `
  --vendor "TeoPlace" `
  --input "build\libs" `
  --main-jar desktopLogin.jar `
  --main-class App `
  --type msi `
  --dest "installer" `
  --icon "icon.ico" `
  --win-dir-chooser --win-menu --win-shortcut --win-console `
  --win-upgrade-uuid 12345678-90ab-cdef-1234-567890abcdef `
  --java-options '--module-path' `
  --java-options '$APPDIR\lib' `
  --java-options '--add-modules' `
  --java-options 'javafx.controls,javafx.fxml'
